/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/korrigan/model.gltf --transform -o public/models/korrigan/Korrigan.jsx 
Files: public/models/korrigan/model.gltf [898.7KB] > C:\websites\gemastik\Beta\Frontend\public\models\korrigan\model-transformed.glb [50.52KB] (94%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { RigidBody } from "@react-three/rapier";

export function Korrigan(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF(
    "./models/korrigan/model-transformed.glb"
  );
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  return (
    <RigidBody type="fixed" colliders="trimesh" {...props}>
      <group ref={group} {...props} dispose={null}>
        <group name="Scene">
          <group name="Armature_vieux" scale={0.151}>
            <primitive object={nodes.root} />
          </group>
          <skinnedMesh
            name="Vieux"
            geometry={nodes.Vieux.geometry}
            material={materials["color_main.001"]}
            skeleton={nodes.Vieux.skeleton}
            scale={0.151}
          />
        </group>
      </group>
    </RigidBody>
  );
}

useGLTF.preload("./models/korrigan/model-transformed.glb");
